apiVersion: apps/v1
kind: Deployment
metadata:
  name: parks-web
  labels:
    customer: David
spec:
  selector:
    matchLabels:
      app: web
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: davidkarim/florida-parks:0.1
        name: web-ctr
        ports:
        - containerPort: 3000
